[package]
name = "tiger"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tiger-rs"
path = "src/main.rs"

[dependencies]
indexmap = "2.0"
mimalloc = { version = "0.1", default-features = false }
rand_mt = { version = "6.0", default-features = false }
rustc-hash = "1.1"

[features]
default = []
debug = []

[profile.release]
opt-level = 3
