#!/bin/bash

# Define an array of category-filename pairs
declare -a pairs=(
    # "datamining correlation"
    # "datamining covariance"
    # "medley deriche"
    # "medley floyd-warshall"
    # "medley nussinov"
    # "stencils adi"
    "stencils fdtd-2d"
    # "stencils heat-3d"
    # "stencils jacobi-1d"
    # "stencils jacobi-2d"
    # "stencils seidel-2d"
)

# Loop through each pair
for pair in "${pairs[@]}"; do
    # Split the pair into category and filename
    CATEGORY=$(echo $pair | awk '{print $1}')
    FILENAME=$(echo $pair | awk '{print $2}')

    echo "Running benchmark for CATEGORY: $CATEGORY, FILENAME: $FILENAME"

    # Run the cargo command and redirect output
    cargo run --release "benchmarks/passing/polybench/${CATEGORY}/${FILENAME}.rs" --interp > "small/${FILENAME}.out"

    # Check if cargo run was successful
    if [ $? -ne 0 ]; then
        echo "Error: Cargo run failed for $CATEGORY/$FILENAME."
        continue  # Skip to the next iteration
    fi

    # Run the post-processing script on the output file
    python3 post.py "small/${FILENAME}.out"
done