pub mod body_contains;
pub mod conditional_invariant_code_motion;
pub mod function_inlining;
pub mod is_resolved;
pub mod is_valid;
pub mod loop_invariant;
pub mod loop_unroll;
pub mod memory;
pub mod passthrough;
mod peepholes;
pub mod purity_analysis;
pub mod switch_rewrites;
